### ISSUE TITLE
segfault on file with lots of parentheses/negation

### ISSUE THREAD

**Issue by langston-barrett** [souffle-lang/souffle#1757]
Souffle f151a8bb4824e15deaa3e8f0764ab520cac1b5a9 crashes with a segfault on this program (generated with Radamsa):
```
.decl expr(x:number)
.output expr()
expr(- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (- (2^31))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))).
```
Here's what GDB says:
```
gdb -q --args ./src/souffle segfault.dl 
Reading symbols from ./src/souffle...                                      
(gdb) run
Starting program: souffle segfault.dl
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/9df65igwjmf2wbw0gbrrgair6piqjgmi-glibc-2.31/lib/libthread_db.so.1".
[Detaching after vfork from child process 20801]

Program received signal SIGSEGV, Segmentation fault.
0x000000000076c3d8 in souffle::interpreter::Engine::execute (this=<error reading variable: Cannot access memory at address 0x7fffff7fc230>, 
    node=0x0, ctxt=<error reading variable: Cannot access memory at address 0x7fffff7fc228>) at interpreter/Engine.cpp:356
356	RamDomain Engine::execute(const Node* node, Context& ctxt) {

(gdb) bt
#0  0x000000000076c3d8 in souffle::interpreter::Engine::execute (
    this=<error reading variable: Cannot access memory at address 0x7fffff7fc230>, node=0x0, 
    ctxt=<error reading variable: Cannot access memory at address 0x7fffff7fc228>) at interpreter/Engine.cpp:356
#1  0x00000000007799cc in souffle::interpreter::Engine::execute(souffle::interpreter::Node const*, souffle::interpreter::Context&)::$_5::operator()() const (this=0x7fffff806ab0) at interpreter/Engine.cpp:486
#2  0x000000000076c4c5 in souffle::interpreter::Engine::execute (this=0x1431ac0, node=0x13ee200, ctxt=...) at interpreter/Engine.cpp:421
#3  0x00000000007799cc in souffle::interpreter::Engine::execute(souffle::interpreter::Node const*, souffle::interpreter::Context&)::$_5::operator()() const (this=0x7fffff80c670) at interpreter/Engine.cpp:486
#4  0x000000000076c4c5 in souffle::interpreter::Engine::execute (this=0x1431ac0, node=0x13eef80, ctxt=...) at interpreter/Engine.cpp:421
```
but the backtrace goes on for a while liike that.

**Comment by XiaowenHu96** [comment]
Hi Langston,
It is a stack-overflow caused by a very deep recursive function call. This is the expected behaviour. 
For this particular use case, I guess something can be done to delay this segfault, e.g. simplification on the expression. However, unless there is a real use case, I do not see a fix is needed.

**Comment by langston-barrett** [comment]
Sounds good to me, thanks @XiaowenHu96!
