### ISSUE TITLE
Segmentation fault on a simple program

### ISSUE THREAD

**Issue by rhendrix42** [souffle-lang/souffle#1774]
Hi guys, 

I get a segfault with the following program:
```
.decl a(x:number) 
.decl b(x:number, y:number) 
.decl c(x:number) 
.decl rejm(A:number, B:number, C:number)
.decl sTXz(A:number, B:number)
.decl ilgC(A:number)
.decl out(A:number)

c(x)  :- a(x), y=0.
rejm(q,V,O) :- b(O,V), a(q).
ilgC(x) :- c(x).
out(Y) :- rejm(f,Y,f), ilgC(c), sTXz(a,b). 

.output out
```

**Souffle version**: 17806893ba9f35dc2e05ca072aff5bc28ad0fe88
**Operating System**: Debian GNU/Linux 10 (buster)
**Kernel**: Linux 4.19.75.1.amd64-smp
**Architecture**: x86-64

**Comment by langston-barrett** [comment]
I can reproduce this. Here's the backtrace from GDB:
```
#0  0x0000000001a8208e in std::type_info::operator== (this=0x1d14be8 <typeinfo for souffle::ast::Clause>, __arg=...)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/typeinfo:122
#1  souffle::ast::Node::operator== (this=0x24a79f0, other=...) at /work/src/./ast/Node.h:58
#2  souffle::ast::Program::removeClause (this=0x24a6460, clause=0x24a7920) at ast/Program.cpp:62
#3  0x0000000000ae4a74 in souffle::ast::removeRelationClauses (tu=..., name=...) at ast/utility/Utils.cpp:112
#4  0x0000000000ae78bb in souffle::ast::removeRelation (tu=..., name=...) at ast/utility/Utils.cpp:102
#5  0x0000000000a01726 in souffle::ast::transform::RemoveRelationCopiesTransformer::removeRelationCopies (translationUnit=...)
    at ast/transform/RemoveRelationCopies.cpp:144
#6  0x000000000050d38e in souffle::ast::transform::RemoveRelationCopiesTransformer::transform (this=<optimized out>, translationUnit=...)
    at /work/src/./ast/transform/RemoveRelationCopies.h:51
#7  0x0000000000a81e96 in souffle::ast::transform::Transformer::apply (this=0x1b552a6 <typeinfo name for souffle::ast::Clause>, 
    translationUnit=...) at ast/transform/Transformer.cpp:25
#8  0x000000000098ec80 in souffle::ast::transform::MetaTransformer::applySubtransformer (this=0x24a3600, translationUnit=..., 
    transformer=0x24a45e0) at ast/transform/Meta.cpp:26
#9  0x0000000000507be6 in souffle::ast::transform::PipelineTransformer::transform (this=0x24a3600, translationUnit=...)
    at /work/src/./ast/transform/Pipeline.h:100
#10 0x0000000000a81e96 in souffle::ast::transform::Transformer::apply (this=0x1b552a6 <typeinfo name for souffle::ast::Clause>, 
    translationUnit=...) at ast/transform/Transformer.cpp:25
#11 0x000000000044181d in souffle::main (argc=<optimized out>, argv=<optimized out>) at main.cpp:551
#12 0x000000000047ffdb in main (argc=28660390, argv=0x24a7920) at main.cpp:735
```

**Comment by langston-barrett** [comment]
FWIW, this input appears pretty different but causes the same crash. Hope it helps with debugging!
```
.type Strin0 <: symbol

.decl input0ata (t:Strin0)
.decl pattern1 (t:Strin0)
.decl pattern2 (t:Strin0)
.decl output0ata (t:Strin0)
.output output0ata ()

output0ata(x) :- pattern2(_), pattern1(y), input0ata(x), match(y, x), match(y, x).

input0ata("a").
input0ata("a00").
input0ata("abab0").
input0ata("aa").
input0ata("aa0a").

pattern1("a."").
pattern2 ("00").
patteattern2(000").
```

**Comment by b-scholz** [comment]
This is related to badly managed analyses in transformers that delete clauses/relations.

**Comment by b-scholz** [comment]
Thanks for detecting all these issues! That is great!

**Comment by rhendrix42** [comment]
> Thanks for detecting all these issues! That is great!

You are welcome @b-scholz  :)
