### ISSUE TITLE
Assertion failure: "the input is neither list nor object format"

### ISSUE THREAD

**Issue by langston-barrett** [souffle-lang/souffle#1777]
On commit 17806893ba9f35dc2e05ca072aff5bc28ad0fe88, when run on this program (generated by AFL - see #1773), Souffle throws an exception:
```
.type List = [
    h000 : number,
    t000 : List
]
.type list = [x:number, y:list]
.decl B(a:number,db:list)

.decl C(x : List)
.input C(IO=jsonfile,filename="0000000000")
.output C(IO=jsonfile, format=object)

.decl D(a:number, b:list)
.input D(IO=jsonfile,Vilename="0000000000")
.output D(IO=jsonfile, format=object)
```
```
Warning: No rules/facts defined for relation B in file prog.dl at line 6
.decl B(a:number,db:list)
------^-------------------
Error loading data: Cannot open json file 0000000000

the input is neither list nor object format
souffle: ./include/souffle/utility/MiscUtil.h:195: void souffle::fatal(const char *, const Args &...) [Args = <>]: Assertion `false && "fatal error; see std err"' failed.
Aborted (core dumped)
```
Here's the backtrace from GDB:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007f19cba04864 in __GI_abort () at abort.c:79
#2  0x00007f19cba04749 in __assert_fail_base (fmt=0x7f19cbb90458 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=0x1b49ca9 "false && \"fatal error; see std err\"", file=0x1b49ccd "./include/souffle/utility/MiscUtil.h", line=195, 
    function=<optimized out>) at assert.c:92
#3  0x00007f19cba16a96 in __GI___assert_fail (assertion=0x1b49ca9 "false && \"fatal error; see std err\"", 
    file=0x1b49ccd "./include/souffle/utility/MiscUtil.h", line=195, 
    function=0x1b4c7b0 "void souffle::fatal(const char *, const Args &...) [Args = <>]") at assert.c:101
#4  0x0000000000663f1e in souffle::fatal<>(char const*) (format=<optimized out>) at /work/src/./include/souffle/utility/MiscUtil.h:195
#5  0x00000000014ecf6c in souffle::ReadStreamJSON::readNextTuple (this=0x2b3e060) at /work/src/./include/souffle/io/ReadStreamJSON.h:89
#6  0x00000000014b7854 in souffle::ReadStream::readAll<souffle::interpreter::RelationWrapper> (this=0x2b3e060, relation=warning: RTTI symbol not found for class 'souffle::interpreter::Relation<2ul, souffle::interpreter::Btree>'
...)
    at /work/src/./include/souffle/io/ReadStream.h:47
#7  0x0000000000c3dc64 in souffle::interpreter::Engine::execute(souffle::interpreter::Node const*, souffle::interpreter::Context&)::$_925::operator()() const (this=<optimized out>) at interpreter/Engine.cpp:1152
#8  souffle::interpreter::Engine::execute (this=<optimized out>, this@entry=0x2b2ed60, node=<optimized out>, ctxt=...)
    at interpreter/Engine.cpp:1143
#9  0x0000000000c2000f in souffle::interpreter::Engine::execute(souffle::interpreter::Node const*, souffle::interpreter::Context&)::$_865::operator()() const (this=<optimized out>) at interpreter/Engine.cpp:1076
#10 souffle::interpreter::Engine::execute (this=this@entry=0x2b2ed60, node=0x2b3d690, ctxt=...) at interpreter/Engine.cpp:1074
#11 0x0000000000c209fb in souffle::interpreter::Engine::execute(souffle::interpreter::Node const*, souffle::interpreter::Context&)::$_923::operator()() const (this=<optimized out>) at interpreter/Engine.cpp:1132
#12 souffle::interpreter::Engine::execute (this=this@entry=0x2b2ed60, node=0x2b3d6d0, ctxt=...) at interpreter/Engine.cpp:1131
#13 0x0000000000c2000f in souffle::interpreter::Engine::execute(souffle::interpreter::Node const*, souffle::interpreter::Context&)::$_865::operator()() const (this=<optimized out>) at interpreter/Engine.cpp:1076
#14 souffle::interpreter::Engine::execute (this=this@entry=0x2b2ed60, node=0x2b3d700, ctxt=...) at interpreter/Engine.cpp:1074
#15 0x0000000000c585ce in souffle::interpreter::Engine::executeMain (this=0x2b2ed60) at interpreter/Engine.cpp:280
#16 0x000000000044ac30 in souffle::main (argc=<optimized out>, argv=<optimized out>) at main.cpp:633
#17 0x000000000047ffdb in main (argc=2, argv=0x7ffcfb3b3c70) at main.cpp:735
```

**Comment by TomasPuverle** [comment]
Hi @langston-barrett, do you have the file which causes the issue?

**Comment by langston-barrett** [comment]
@TomasPuverle Yes, the first block of code in my original comment should cause the crash described.

**Comment by TomasPuverle** [comment]
Hi Langston,

I am afraid I can't reproduce on master, which is why I asumed (based on the output) that perhaps the second file was present and the abort happened while reading it (since the stacktrace specifically shows reading a JSON file)

This is the output I get (on 64-bit Linux) with latest master.

```
➜  souffle git:(master) ✗ src/souffle bug/bug.dl 
Warning: No rules/facts defined for relation B in file bug.dl at line 6
.decl B(a:number,db:list)
------^-------------------
Error loading data: Cannot open json file 0000000000

Error loading data: Cannot open json file 0000000000
```

Could you please provide more information, or try with master to see if the issue is resolved?
Thanks!

**Comment by langston-barrett** [comment]
@TomasPuverle Sure thing, I'll reopen this if I can reproduce the issue again.

**Comment by mmcgr** [comment]
The difference may be because of `Vilename` instead of `filename`. A first run can work, and produces the default named `D.json`, with one line - `[]`. The second run loads `D.json`, then fails to parse `[]`, then exits.

**Comment by TomasPuverle** [comment]
You are right.  I must have unconsciously corrected the spelling.
Now that I copied the example again, I get the error reported.
@langston-barrett, please re-open.  My apologies.
