### ISSUE TITLE
Assertion failure in ValueTranslator: "variable not grounded"

### ISSUE THREAD

**Issue by langston-barrett** [souffle-lang/souffle#1924]
```
#3  0x00007f0f16365f36 in __GI___assert_fail (assertion=0x55e72baeffe0 "index.isDefined(var) && \"variable not grounded\"", 
    file=0x55e72baeffb8 "ast2ram/seminaive/ValueTranslator.cpp", line=47, 
    function=0x55e72baeff00 "virtual souffle::Own<souffle::ram::Expression> souffle::ast2ram::seminaive::ValueTranslator::visit_(souffle::type_identity<souffle::ast::Variable>, const souffle::ast::Variable&)") at assert.c:101
```
```
$ souffle --version
Souffle: 2.0.2-987-gbcb2a08e5(32bit Domains)
Copyright (c) 2016-19 The Souffle Developers.
Copyright (c) 2013-16 Oracle and/or its affiliates.
```
This started happening right after I added the following (possibly malformed) rule to my program:
```
  // Choose a single representative from each equivalence class under "unify".
  .decl unify_repr(?aCtx: Context, ?alloc: Allocation, ?reprCtx: Context, ?repr: Allocation)
  unify_repr(?aCtx, ?alloc, ?reprCtx, ?repr) :-
    unify([?aCtx, ?alloc], [?reprCtx, ?repr]),
    ?minCtx = min o : {
      unify([?aCtx, ?alloc], [?ctx, _]),
      o = ord(?ctx)
    },
    ?minAlloc = min o : {
      unify([?aCtx, ?alloc], [?ctx, ?alloc]),
      ?minCtx = ord(?ctx),
      o = ord(?alloc)
    },
    ?minCtx = ord(?reprCtx),
    ?minAlloc = ord(?repr).
```
FWIW, the above rule is inside a component. Let me know if the problem is not obvious and I can spend some time trying to create a minimal program that triggers the same behavior, and/or reproduce with a more recent version of Souffle with debug symbols.

**Comment by b-scholz** [comment]
Can you reduce it to a small stand-alone program?

**Comment by langston-barrett** [comment]
> Can you reduce it to a small stand-alone program?

I just tried the naive approach of copying the rule I posted above to its own file and wasn't met with success... I can keep trying, but in the meantime here's the backtrace from Souffle HEAD (https://github.com/souffle-lang/souffle/commit/17bef0b5d97d2fad198770b8173f3155c05d89c5):

```
gdb -q --batch --eval-command=run --eval-command=bt --args souffle -j 24 -L .out/build/llvm -lFunctors llvm/PointerAnalysis/datalog/debug.project -F .out/cache/pointer-analysis/exceptions-min.bc.facts -D .out/cache/pointer-analysis/exceptions-min.bc.results
```
```
souffle: ast2ram/seminaive/ValueTranslator.cpp:47: virtual souffle::Own<souffle::ram::Expression> souffle::ast2ram::seminaive::ValueTranslator::visit_(souffle::type_identity<souffle::ast::Variable>, const souffle::ast::Variable&): Assertion `index.isDefined(var.getName()) && "variable not grounded"' failed.

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ff10b305859 in __GI_abort () at abort.c:79
#2  0x00007ff10b305729 in __assert_fail_base (fmt=0x7ff10b49b588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x5606fafe7ce0 "index.isDefined(var.getName()) && \"variable not grounded\"", file=0x5606fafe7cb8 "ast2ram/seminaive/ValueTranslator.cpp", line=47, function=<optimized out>) at assert.c:92
#3  0x00007ff10b316f36 in __GI___assert_fail (assertion=assertion@entry=0x5606fafe7ce0 "index.isDefined(var.getName()) && \"variable not grounded\"", file=file@entry=0x5606fafe7cb8 "ast2ram/seminaive/ValueTranslator.cpp", line=line@entry=47, function=function@entry=0x5606fafe7c00 "virtual souffle::Own<souffle::ram::Expression> souffle::ast2ram::seminaive::ValueTranslator::visit_(souffle::type_identity<souffle::ast::Variable>, const souffle::ast::Variable&)") at assert.c:101
#4  0x00005606fabf6610 in souffle::ast2ram::seminaive::ValueTranslator::visit_ (this=0x7ffc1f4cd2d0, var=...) at ast2ram/seminaive/ValueTranslator.cpp:46
#5  souffle::ast2ram::seminaive::ValueTranslator::visit_ (this=0x7ffc1f4cd2d0, var=...) at ast2ram/seminaive/ValueTranslator.cpp:46
#6  0x00005606fabf8208 in souffle::ast::Visitor<std::unique_ptr<souffle::ram::Expression, std::default_delete<souffle::ram::Expression> >, souffle::ast::Node const>::dispatch (node=..., this=0x7ffc1f4cd2d0) at ./include/souffle/utility/MiscUtil.h:211
#7  souffle::Visitor<std::unique_ptr<souffle::ram::Expression, std::default_delete<souffle::ram::Expression> >, souffle::ast::Node const>::operator() (node=..., this=0x7ffc1f4cd2d0) at ./include/souffle/utility/Visitor.h:89
#8  souffle::ast2ram::seminaive::ValueTranslator::translateValue (this=<optimized out>, arg=0x5606fd03f890) at ast2ram/seminaive/ValueTranslator.cpp:43
#9  0x00005606fabf6a0c in souffle::ast2ram::seminaive::ValueTranslator::visit_ (this=0x7ffc1f4cd3f0, inf=...) at ast2ram/seminaive/ValueTranslator.cpp:87
#10 0x00005606fabf826c in souffle::ast::Visitor<std::unique_ptr<souffle::ram::Expression, std::default_delete<souffle::ram::Expression> >, souffle::ast::Node const>::dispatch (node=..., this=0x7ffc1f4cd3f0) at ./include/souffle/utility/MiscUtil.h:211
#11 souffle::Visitor<std::unique_ptr<souffle::ram::Expression, std::default_delete<souffle::ram::Expression> >, souffle::ast::Node const>::operator() (node=..., this=0x7ffc1f4cd3f0) at ./include/souffle/utility/Visitor.h:89
#12 souffle::ast2ram::seminaive::ValueTranslator::translateValue (this=<optimized out>, arg=0x5606fd047c00) at ast2ram/seminaive/ValueTranslator.cpp:43
#13 0x00005606fabfebd5 in souffle::ast2ram::TranslatorContext::translateValue (this=<optimized out>, index=..., arg=0x5606fd047c00) at ast2ram/utility/TranslatorContext.cpp:232
#14 0x00005606fafa41bd in souffle::ast2ram::seminaive::ConstraintTranslator::visit_ (this=0x7ffc1f4cd4c0, binRel=...) at /usr/include/c++/9/bits/unique_ptr.h:360
#15 0x00005606fafa4e34 in souffle::ast::Visitor<std::unique_ptr<souffle::ram::Condition, std::default_delete<souffle::ram::Condition> >, souffle::ast::Node const>::dispatch (node=..., this=0x7ffc1f4cd4c0) at ./include/souffle/utility/MiscUtil.h:211
#16 souffle::Visitor<std::unique_ptr<souffle::ram::Condition, std::default_delete<souffle::ram::Condition> >, souffle::ast::Node const>::operator() (node=..., this=0x7ffc1f4cd4c0) at ./include/souffle/utility/Visitor.h:89
#17 souffle::ast2ram::seminaive::ConstraintTranslator::translateConstraint (this=<optimized out>, lit=0x5606fd0d21e0) at ast2ram/seminaive/ConstraintTranslator.cpp:31
#18 0x00005606fabfec55 in souffle::ast2ram::TranslatorContext::translateConstraint (this=<optimized out>, index=..., lit=0x5606fd0d21e0) at ast2ram/utility/TranslatorContext.cpp:239
#19 0x00005606fabd81f3 in souffle::ast2ram::seminaive::ClauseTranslator::instantiateAggregator (this=0x5606fefcdbd0, op=std::unique_ptr<class souffle::ram::Operation> = {...}, clause=..., agg=0x5606fd18ca50, curLevel=3) at /usr/include/c++/9/bits/unique_ptr.h:360
#20 0x00005606fabdc8a9 in souffle::ast2ram::seminaive::ClauseTranslator::addGeneratorLevels (this=0x5606fefcdbd0, op=std::unique_ptr<class souffle::ram::Operation> = {...}, clause=...) at /usr/include/c++/9/bits/move.h:74
#21 0x00005606fabdff4d in souffle::ast2ram::seminaive::ClauseTranslator::createRamRuleQuery (this=0x5606fefcdbd0, clause=...) at /usr/include/c++/9/bits/move.h:74
#22 0x00005606fabd6bf3 in souffle::ast2ram::seminaive::ClauseTranslator::translateNonRecursiveClause (this=0x5606fefcdbd0, clause=...) at ast2ram/seminaive/ClauseTranslator.cpp:133
#23 0x00005606fabfeac2 in souffle::ast2ram::TranslatorContext::translateNonRecursiveClause (this=<optimized out>, clause=...) at ast2ram/utility/TranslatorContext.cpp:220
#24 0x00005606fabe8f8b in souffle::ast2ram::seminaive::UnitTranslator::generateNonRecursiveRelation (this=0x5606fcc48290, rel=...) at /usr/include/c++/9/bits/unique_ptr.h:360
#25 0x00005606fabeef72 in souffle::ast2ram::seminaive::UnitTranslator::generateStratum (this=0x5606fcc48290, scc=889) at ast2ram/seminaive/UnitTranslator.cpp:166
#26 0x00005606fabef491 in souffle::ast2ram::seminaive::UnitTranslator::generateProgram (this=0x5606fcc48290, translationUnit=...) at /usr/include/c++/9/bits/stl_vector.h:1107
#27 0x00005606fabe7fb5 in souffle::ast2ram::seminaive::UnitTranslator::translateUnit (this=0x5606fcc48290, tu=...) at ast2ram/seminaive/UnitTranslator.cpp:512
#28 0x00005606faa3ef1a in souffle::main (argc=<optimized out>, argv=<optimized out>) at /usr/include/c++/9/bits/unique_ptr.h:360
#29 0x00007ff10b3070b3 in __libc_start_main (main=0x5606faa41380 <main(int, char**)>, argc=11, argv=0x7ffc1f4cfda8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffc1f4cfd98) at ../csu/libc-start.c:308
#30 0x00005606faa471ae in _start () at main.cpp:755
```

**Comment by langston-barrett** [comment]
I also attempted some automatic minimization with [halfempty](https://github.com/googleprojectzero/halfempty) but that didn't work well enough either.

**Comment by b-scholz** [comment]
It seems that the aggregate translation in the ast2ram translator has issues for your given problem.
It should be an isolated problem.

Your aggregates have complex sub-clauses. Please can you post the transformed Datalog program for your rule. I assume that the aggregate materialisation has issues, which then breaks the ast2ram translator. 

I would suggest: (1) run your program with --show=transformed-datalog, (2) find the rule in the transformed program, and (3) extract the materialisation relations and their rules and the failing rule with its relation, (4) add dummy facts to all relations so that they are not eliminated, and (5) check whether you can reproduce the problem.

**Comment by b-scholz** [comment]
I could not reproduce the issue with the HEAD version of soufflé. I have produced a small stand-alone program
```
.type Allocation = number
.type Context = number
.type ContextAlloc = [x:Context, y:Allocation]

.decl unify(x:ContextAlloc, y:ContextAlloc)
unify([1,2],[2,3]).

.decl unify_repr(?aCtx: Context, ?alloc: Allocation, ?reprCtx: Context, ?repr: Allocation)
  unify_repr(?aCtx, ?alloc, ?reprCtx, ?repr) :-
    unify([?aCtx, ?alloc], [?reprCtx, ?repr]),
    ?minCtx = min o : {
      unify([?aCtx, ?alloc], [?ctx, _]),
      o = ord(?ctx)
    },
    ?minAlloc = min o : {
      unify([?aCtx, ?alloc], [?ctx, ?alloc]),
      ?minCtx = ord(?ctx),
      o = ord(?alloc)
    },
    ?minCtx = ord(?reprCtx),
    ?minAlloc = ord(?repr).

.printsize unify_repr
```
that is transformed to
```
.type Allocation = number
.type Context = number
.type ContextAlloc = [x:Context, y:Allocation]
.decl unify(x:ContextAlloc, y:ContextAlloc) 
.decl unify_repr(?aCtx:Context, ?alloc:Allocation, ?reprCtx:Context, ?repr:Allocation) 
.decl __agg_subclause(?aCtx:Context, ?alloc:Allocation, ?ctx:Context, ?minCtx:__numberConstant, o:__numberConstant) 
unify([1,2],[2,3]).

unify_repr(?aCtx,?alloc,?reprCtx,?repr) :- 
   unify([?aCtx,?alloc],[?reprCtx,?repr]),
   ord(?reprCtx) = min ord(?ctx0) : { unify([?aCtx,?alloc],[?ctx0,+underscore_0]),ord(?ctx0) = ord(?ctx0) },
   ord(?repr) = min o : { __agg_subclause(?aCtx,?alloc,+underscore_1,ord(?reprCtx),o) }.

__agg_subclause(?aCtx,?alloc,?ctx,ord(?ctx),ord(?alloc)) :- 
   unify([?aCtx,?alloc],[?ctx,?alloc]).
```
which works.

**Comment by langston-barrett** [comment]
I'll close this until/unless I can reproduce the issue with a small example. It's not blocking me, it just came up during development and I figured I'd share in case the issue was obvious.
