### ISSUE TITLE
crash when using `range` in the `count` aggregate 

### ISSUE THREAD

**Issue by quentin** [souffle-lang/souffle#2160]
Hi,
This simple program crashes with the interpreter. Is this construction allowed? If not it should be detected and rejected.

```
.decl count_even(cnt:number)
.output count_even
count_even(cnt) :-
  cnt = count : { i = range(0,10), i % 2 = 0 }.
```

Bottom of the stack is:
```
#0  0x0000000000bc45dd in souffle::interpreter::Order::operator[] (this=0x14a0748, idx=0) at /home/quentin/projects/souffle/src/interpreter/Index.h:125                 
#1  0x0000000000bc2aab in souffle::interpreter::NodeGenerator::OrderingContext::mapOrder (this=0x7fffffffc408, tupleId=1, elementId=0) at /home/quentin/projects/souffle/src/interpreter/Generator.cpp:789
#2  0x0000000000bbc140 in souffle::interpreter::NodeGenerator::visit_ (this=0x7fffffffc300, access=...) at /home/quentin/projects/souffle/src/interpreter/Generator.cpp:65
#3  0x0000000000b7e6f9 in souffle::ram::Visitor<std::unique_ptr<souffle::interpreter::Node, std::default_delete<souffle::interpreter::Node> >, souffle::ram::Node const>::dispatch (this=0x7fffffffc300, node=...)
    at /home/quentin/projects/souffle/src/ram/utility/Visitor.h:118
```

The generated c++ code does not compile:
```
./souffleAQe4gJ.cpp: In lambda function:
./souffleAQe4gJ.cpp:260:28: error: ‘env1’ was not declared in this scope; did you mean ‘env0’?
  260 | if( (ramBitCast<RamDomain>(env1[0]) == ramBitCast<RamDomain>(env1[0])) && (ramBitCast<RamDomain>((ramBitCast<RamSigned>(env1[0]) % ramBitCast<RamSigned>(RamSigned(2)))) == ramBitCast<RamDomain>(RamSigned(0)))) {
      |                            ^~~~
      |                            env0
failed to compile C++ source <./souffleAQe4gJ.cpp>
```

The transformed AST is:
```
count_even(@generator_1) :- 
   @generator_0 = range(0,10),
   @generator_1 = count : { @generator_0 = @generator_0,(@generator_0%2) = 0,+Tautology() }.
```

In the transformed RAM is, `t1` seems to be used before its definition:
```
 SUBROUTINE stratum_1
  DEBUG "count_even(@generator_1) :- \n   @generator_0 = range(0,10),\n   @generator_1 = count : { @generator_0 = @generator_0,(@generator_0%2) = 0,+Tautology() }.\nin file /home/quentin/projects/souffle/foo.dl [4:1-5:48]"
   QUERY
    t0.0 = count FOR ALL t0 IN +Tautology WHERE ((t1.0 = t1.0) AND ((t1.0%NUMBER(2)) = NUMBER(0)))
     IF (t0.0 = t0.0)
      RANGE(NUMBER(0),NUMBER(10)) INTO t1
       IF (t1.0 = t1.0)
        INSERT (t0.0) INTO count_even
   END QUERY
  END DEBUG
```

Quentin

**Comment by b-scholz** [comment]
We have never tested range in aggregates.
