### ISSUE TITLE
Assertion failure in ast::reorderAtoms involving subsumption and query plans

### ISSUE THREAD

**Issue by langston-barrett** [souffle-lang/souffle#2225]
```
souffle --version 
Souffle: 2.2-129-gfce85d9ec(32bit Domains)
Copyright (c) 2016-19 The Souffle Developers.
Copyright (c) 2013-16 Oracle and/or its affiliates.
```
Minimal reproduction:
```
.decl refl(x: number, u: number, z: number)
.decl unify(x: number, y: number)

refl(0, 0, 0).
refl(x, y, x) :- unify(x, y).
unify(x, y) :- refl(x, y, _).

unify(x, y) <=
  unify(y, x) :-
    refl(x, y, _),
    unify(x, y).
.plan 0: (1, 2),
      1: (2, 1)

.output refl
.output unify
```
```
$ souffle test.dl
souffle: ../src/ast/utility/Utils.cpp:154: std::vector<Atom *> souffle::ast::reorderAtoms(const std::vector<Atom *> &, const std::vector<std::size_t> &): Assertion `newOrder.size() == atoms.size()' failed.
Aborted (core dumped)
```
Here's the backtrace from GDB:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f8b1aa4a859 in __GI_abort () at abort.c:79
#2  0x00007f8b1aa4a729 in __assert_fail_base (fmt=0x7f8b1abe0588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=0x29a0fa "newOrder.size() == atoms.size()", file=0x2db35a "../src/ast/utility/Utils.cpp", line=154, 
    function=<optimized out>) at assert.c:92
#3  0x00007f8b1aa5bf36 in __GI___assert_fail (assertion=0x29a0fa "newOrder.size() == atoms.size()", 
    file=0x2db35a "../src/ast/utility/Utils.cpp", line=154, 
    function=0x2db377 "std::vector<Atom *> souffle::ast::reorderAtoms(const std::vector<Atom *> &, const std::vector<std::size_t> &)") at assert.c:101
#4  0x00000000006138d2 in souffle::ast::reorderAtoms (atoms=..., newOrder=...) at ../src/ast/utility/Utils.cpp:154
#5  0x0000000000633805 in souffle::ast2ram::seminaive::ClauseTranslator::getAtomOrdering (this=<optimized out>, 
    clause=...) at ../src/ast2ram/seminaive/ClauseTranslator.cpp:708
#6  0x0000000000634371 in souffle::ast2ram::seminaive::ClauseTranslator::indexAtoms (this=0x1783830, clause=...)
    at ../src/ast2ram/seminaive/ClauseTranslator.cpp:771
#7  0x000000000062d8c0 in souffle::ast2ram::seminaive::ClauseTranslator::indexClause (this=0x1783830, clause=...)
    at ../src/ast2ram/seminaive/ClauseTranslator.cpp:834
#8  souffle::ast2ram::seminaive::ClauseTranslator::createRamRuleQuery (this=0x1783830, clause=...)
    at ../src/ast2ram/seminaive/ClauseTranslator.cpp:199
#9  0x000000000062d79e in souffle::ast2ram::seminaive::ClauseTranslator::translateNonRecursiveClause (this=0x1783830, 
    clause=...) at ../src/ast2ram/seminaive/ClauseTranslator.cpp:135
#10 0x000000000064d119 in souffle::ast2ram::TranslatorContext::translateNonRecursiveClause (this=<optimized out>, 
    clause=..., mode=<optimized out>) at ../src/ast2ram/utility/TranslatorContext.cpp:218
#11 0x000000000063ae5a in souffle::ast2ram::seminaive::UnitTranslator::generateNonRecursiveDelete (this=0x177db70, 
    scc=...) at ../src/ast2ram/seminaive/UnitTranslator.cpp:398
#12 0x000000000063e419 in souffle::ast2ram::seminaive::UnitTranslator::generateStratumPreamble (this=0x177db70, 
    scc=...) at ../src/ast2ram/seminaive/UnitTranslator.cpp:436
#13 0x000000000063a9d8 in souffle::ast2ram::seminaive::UnitTranslator::generateRecursiveStratum (this=0x177db70, 
    scc=...) at ../src/ast2ram/seminaive/UnitTranslator.cpp:564
#14 0x0000000000639e9d in souffle::ast2ram::seminaive::UnitTranslator::generateStratum (this=0x177db70, scc=0)
    at ../src/ast2ram/seminaive/UnitTranslator.cpp:168
#15 0x0000000000640aa3 in souffle::ast2ram::seminaive::UnitTranslator::generateProgram (this=0x177db70, 
    translationUnit=...) at ../src/ast2ram/seminaive/UnitTranslator.cpp:703
#16 0x0000000000641218 in souffle::ast2ram::seminaive::UnitTranslator::translateUnit (this=0x177db70, tu=...)
    at ../src/ast2ram/seminaive/UnitTranslator.cpp:738
#17 0x00000000004bbeb2 in souffle::main (argc=<optimized out>, argv=<optimized out>) at ../src/main.cpp:673
#18 0x00007f8b1aa4c0b3 in __libc_start_main (main=0x4c2de0 <main(int, char**)>, argc=2, argv=0x7ffcd3bae968, 
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffcd3bae958)
    at ../csu/libc-start.c:308
#19 0x00000000004b554e in _start ()
```

**Comment by b-scholz** [comment]
You need one more element in your permutation vectors for the plan statement. There are hidden atoms in a subsumption clause.

**Comment by b-scholz** [comment]
But indeed it should not crash - it should demand a vector of the right length.
